Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Description: Checks that `required_ruby_version` of gemspec and `TargetRubyVersion` of
    .rubocop.yml are equal.
  Enabled: false
  Include:
    - '**/*.gemspec'

Gemspec/RubyVersionGlobalsUsage:
  Enabled: true
